### ISSUE TITLE
Always Run

### ISSUE THREAD

**Issue by EscVM** [telmomarques/xiaomi-360-1080p-video-stream#1]
Hi @telmomarques!

Thank you for your work. Is there a way to run the script automatically when the camera is powered on? Moreover, is it possible to re-start the process if for some reasons has crashed?

Thank you for your help!

**Comment by telmomarques** [comment]
Hi!

I'm currently working on an implementation that uses [runit](http://smarden.org/runit/) instead of the current solution. This new implementation treats each hack as a service, thus providing the behavior you mention.

I'll be releasing it in the near future, as soon as it's stable. Will be posting updates here.

**Comment by EscVM** [comment]
Thank you! I'll try it. 

One more thing...do you know why some times the streaming is distorted with strange gray frames? It seems not related with any specific action. Moreover, I was using OpcenCV to capture the video streaming and I was wondering if you know some post processing to mask this streaming errors.

**Comment by telmomarques** [comment]
It's probably due to missing i-frames from the stream, this implementation is really not stable and I dropped it.

You should look for the RTSP prototype available on the telegram group, it's still very unstable but better then this project!

https://t.me/mijav4RTSP

**Comment by EscVM** [comment]
Yes I know, but what I like of this implementation is that I can easily access the frames with OpenCV. Instead, RTSP does not always work with OpenCV.

> It's probably due to missing i-frames from the stream, this implementation is really not stable and > I dropped it.

Yep, I supposed it was for that reason, but I can't really figure it out why.

**Comment by telmomarques** [comment]
If you look at the source file "video_direct_memory_access.c" you'll see it's running a `while(1)` loop, so my best guess is that sometimes the program doesn't catch some frames on time, or the frames might be incomplete.

There's no way of knowing when a frame is complete, so the program just tries to grab as many different frames as possible.
